### ISSUE TITLE
Trying to run the webapp with docker and first it had wrong npm & yarn so I switched to npm 8 and ran into new errors! 

### ISSUE THREAD

**Issue by horsecoin** [smokenetwork/webapp#63]
Heres my latest error to work through. Anyone know this one? 

coininstant@honusurf:~/webapp$ docker build -t=hightimes/smokenetwork:webapp .
Sending build context to Docker daemon  22.42MB
Step 1/12 : FROM node:8
8: Pulling from library/node
e79bb959ec00: Pull complete 
d4b7902036fe: Pull complete 
1b2a72d4e030: Pull complete 
d54db43011fd: Pull complete 
69d473365bb3: Pull complete 
6e2490ee2dc8: Pull complete 
fc66dfb5c5fd: Pull complete 
f0614876c4bf: Pull complete 
Digest: sha256:918f0be3932f555cd2645ca828b9c231a2dab10d9cf2dbb58896411207bbe52f
Status: Downloaded newer image for node:8
 ---> 8c51cec97ebf
Step 2/12 : RUN npm install -g yarn
 ---> Running in 87fe67330bb1
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.15.2
added 1 package in 1.024s
Removing intermediate container 87fe67330bb1
 ---> e52e4ded871f
Step 3/12 : WORKDIR /var/app
 ---> Running in ee886ccdc8e2
Removing intermediate container ee886ccdc8e2
 ---> ebe93526f44a
Step 4/12 : RUN mkdir -p /var/app
 ---> Running in 9d5cbcd65d7a
Removing intermediate container 9d5cbcd65d7a
 ---> b5494bb8fbc9
Step 5/12 : ADD package.json /var/app/package.json
 ---> 61c6f1fe81f2
Step 6/12 : RUN yarn
 ---> Running in 9b4c485b52aa
yarn install v1.15.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @smokenetwork/smoke-js > postinstall-build@5.0.3: postinstall-build's behavior is now built into npm! You should migrate off of postinstall-build and use the new `prepare` lifecycle script with npm 5.0.0 or greater.
warning autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
warning autoprefixer-loader > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning grant-koa > grant > request > hawk > cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
warning grant-koa > grant > request > hawk > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning grant-koa > grant > request > hawk > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning grant-koa > grant > request > hawk > cryptiles > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning grant-koa > grant > request > hawk > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning grant-koa > grant > request > hawk > sntp > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning koa-body > formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
warning koa-compressor > mz > native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
warning purest > request > node-uuid@1.4.8: Use uuid module instead
warning react > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning sequelize-cli > gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning sequelize-cli > gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning sequelize-cli > gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning sequelize-cli > gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning sequelize-cli > gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning sequelize-cli > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning sequelize-cli > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning sinon > formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
warning sinon > samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
warning sinon > formatio > samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
warning supertest > superagent > formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
warning webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
warning store@1.3.20: The engine "browser" appears to be invalid.
[4/5] Linking dependencies...
warning " > estraverse-fb@1.3.2" has unmet peer dependency "estraverse@*".
warning "react-foundation-components > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
warning "react-foundation-components > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
warning " > react-ga@2.5.7" has unmet peer dependency "prop-types@^15.6.0".
warning " > react-ga@2.5.7" has incorrect peer dependency "react@^15.6.2 || ^16.0".
warning " > react-intl@2.8.0" has unmet peer dependency "prop-types@^15.5.4".
warning " > react-router-scroll@0.4.4" has unmet peer dependency "history@^2.0.0 || ^3.0.0".
warning " > svgo-loader@1.2.1" has unmet peer dependency "svgo@>=0.4.0".
warning " > co-mocha@1.2.2" has incorrect peer dependency "mocha@>=1.18 <6".
warning " > eslint-config-airbnb@15.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 152.82s.
Removing intermediate container 9b4c485b52aa
 ---> fc4baaeb1080
Step 7/12 : COPY . /var/app
 ---> 7b7e868e7e12
Step 8/12 : RUN mkdir tmp &&   npm test &&   npm run-script build
 ---> Running in 7b9041638fba

> smoke.io@0.1.0 test /var/app
> npm run mocha -- src/app/**/*.test.js src/shared/**/*.test.js

> smoke.io@0.1.0 mocha /var/app
> NODE_ENV=test mocha ./mocha.setup.js "src/app/redux/FetchDataSaga.test.js" "src/app/utils/FormatDecimal.test.js" "src/app/utils/Links.test.js" "src/app/utils/ProxifyUrl.test.js" "src/shared/**/*.test.js"

  formatDecimal
    ✓ should format decimals

  Links
    ✓ all
    ✓ multiple matches
    ✓ by domain
    ✓ by image

  Performance
    ✓ any, 20480 bytes x 10,000 (187ms)
    ✓ image (large), 20480 bytes x 10,000 (125ms)
    ✓ image, 20480 bytes x 10,000 (205ms)
    ✓ remote, 20480 bytes x 10,000 (313ms)
    ✓ youTube
    ✓ youTubeId

  ProxifyUrl
    ✓ naked URL
    ✓ naked steemit hosted URL
    1) proxied steemit hosted URL
    2) proxied URL
    3) double-proxied URL
    4) preserve dimensions - single-proxied URL
    5) preserve dimensions - double-proxied URL
    6) preserve dimensions - strip proxies & dimensions when appropriate

  htmlready
TypeError: Cannot read property 'prefix' of null
    ✓ should return plain text without html unmolested
    ✓ should allow links where the text portion and href contains smoke.io
    7) should not allow links where the text portion contains smoke.io but the link does not
    ✓ should allow more than one link per post

  16 passing (920ms)
  7 failing

  1) ProxifyUrl
       proxied steemit hosted URL:

      AssertionError [ERR_ASSERTION]: (https://steemitimages.com/0x0/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg, 256x512) should return https://steemitimages.com/256x512/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg. output was https://steemitimages.com/256x512/https://steemitimages.com/0x0/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg
      + expected - actual

      -https://steemitimages.com/256x512/https://steemitimages.com/0x0/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg
      +https://steemitimages.com/256x512/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg
      
      at testCase (src/app/utils/ProxifyUrl.test.js:60:10)
      at Context.<anonymous> (src/app/utils/ProxifyUrl.test.js:20:5)

  2) ProxifyUrl
       proxied URL:

      AssertionError [ERR_ASSERTION]: (https://steemitimages.com/0x0/https://example.com/img.png, 100x200) should return https://steemitimages.com/100x200/https://example.com/img.png. output was https://steemitimages.com/100x200/https://steemitimages.com/0x0/https://example.com/img.png
      + expected - actual

      -https://steemitimages.com/100x200/https://steemitimages.com/0x0/https://example.com/img.png
      +https://steemitimages.com/100x200/https://example.com/img.png
      
      at testCase (src/app/utils/ProxifyUrl.test.js:60:10)
      at Context.<anonymous> (src/app/utils/ProxifyUrl.test.js:24:5)

  3) ProxifyUrl
       double-proxied URL:

      AssertionError [ERR_ASSERTION]: (https://steemitimages.com/0x0/https://steemitimages.com/0x0/https://example.com/img.png, 100x200) should return https://steemitimages.com/100x200/https://example.com/img.png. output was https://steemitimages.com/100x200/https://steemitimages.com/0x0/https://steemitimages.com/0x0/https://example.com/img.png
      + expected - actual

      -https://steemitimages.com/100x200/https://steemitimages.com/0x0/https://steemitimages.com/0x0/https://example.com/img.png
      +https://steemitimages.com/100x200/https://example.com/img.png
      
      at testCase (src/app/utils/ProxifyUrl.test.js:60:10)
      at Context.<anonymous> (src/app/utils/ProxifyUrl.test.js:29:5)

  4) ProxifyUrl
       preserve dimensions - single-proxied URL:

      AssertionError [ERR_ASSERTION]: (https://steemitdevimages.com/100x200/https://example.com/img.png, true) should return https://steemitimages.com/100x200/https://example.com/img.png. output was https://steemitdevimages.com/100x200/https://example.com/img.png
      + expected - actual

      -https://steemitdevimages.com/100x200/https://example.com/img.png
      +https://steemitimages.com/100x200/https://example.com/img.png
      
      at testCase (src/app/utils/ProxifyUrl.test.js:60:10)
      at Context.<anonymous> (src/app/utils/ProxifyUrl.test.js:34:5)

  5) ProxifyUrl
       preserve dimensions - double-proxied URL:

      AssertionError [ERR_ASSERTION]: (https://steemitimages.com/100x200/https://steemitimages.com/0x0/https://example.com/img.png, true) should return https://steemitimages.com/100x200/https://example.com/img.png. output was https://steemitimages.com/0x0/https://steemitimages.com/100x200/https://steemitimages.com/0x0/https://example.com/img.png
      + expected - actual

      -https://steemitimages.com/0x0/https://steemitimages.com/100x200/https://steemitimages.com/0x0/https://example.com/img.png
      +https://steemitimages.com/100x200/https://example.com/img.png
      
      at testCase (src/app/utils/ProxifyUrl.test.js:60:10)
      at Context.<anonymous> (src/app/utils/ProxifyUrl.test.js:40:5)

  6) ProxifyUrl
       preserve dimensions - strip proxies & dimensions when appropriate:

      AssertionError [ERR_ASSERTION]: (https://steemitimages.com/0x0/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg, true) should return https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg. output was https://steemitimages.com/0x0/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg
      + expected - actual

      -https://steemitimages.com/0x0/https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg
      +https://steemitimages.com/DQmaJe2Tt5kmVUaFhse1KTEr4N1g9piMgD3YjPEQhkZi3HR/30day-positivity-challenge.jpg
      
      at testCase (src/app/utils/ProxifyUrl.test.js:60:10)
      at Context.<anonymous> (src/app/utils/ProxifyUrl.test.js:48:5)

  7) htmlready
       should not allow links where the text portion contains smoke.io but the link does not:

      AssertionError: expected '<xml xmlns="http://www.w3.org/1999/xhtml"><a href="https://steamit.com/signup" xmlns="http://www.w3.org/1999/xhtml">https://smoke.io/signup</a></xml>' to equal '<xml xmlns="http://www.w3.org/1999/xhtml"><div title="missing translation: en.g.phishy_message" class="phishy">https://smoke.io/signup / https://steamit.com/signup</div></xml>'
      + expected - actual

      -<xml xmlns="http://www.w3.org/1999/xhtml"><a href="https://steamit.com/signup" xmlns="http://www.w3.org/1999/xhtml">https://smoke.io/signup</a></xml>
      +<xml xmlns="http://www.w3.org/1999/xhtml"><div title="missing translation: en.g.phishy_message" class="phishy">https://smoke.io/signup / https://steamit.com/signup</div></xml>
      
      at Context.<anonymous> (src/shared/HtmlReady.test.js:29:20)

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! smoke.io@0.1.0 mocha: `NODE_ENV=test mocha ./mocha.setup.js "src/app/redux/FetchDataSaga.test.js" "src/app/utils/FormatDecimal.test.js" "src/app/utils/Links.test.js" "src/app/utils/ProxifyUrl.test.js" "src/shared/**/*.test.js"`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the smoke.io@0.1.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-31T23_07_25_761Z-debug.log
npm ERR! Test failed.  See above for more details.
The command '/bin/sh -c mkdir tmp &&   npm test &&   npm run-script build' returned a non-zero code: 1
coininstant@honusurf:~/webapp$

**Comment by horsecoin** [comment]
Closing I later found another set of diretions.
